# Generated by Django 3.2.9 on 2021-11-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=303)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=303)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=80)),
                ('zipcode', models.CharField(max_length=50)),
            ],
        ),
    ]
